title: <p align="center"> Maja Kucharczyk </p>
logo: /assets/img/headshot_circle.jpg

description:
  <p align="center">
  <a href="https://www.datacamp.com/certificate/DS0023102746140">Certification</a> |
  <a href="https://www.linkedin.com/in/maja-kucharczyk/">LinkedIn</a> |
  <a href="https://scholar.google.ca/citations?user=3uFCBMYAAAAJ&hl=en">Google Scholar</a>
  </p>
  
  <p align="justify">
  Hi, Iâ€™m Maja (My-a). I have a PhD in geography and expertise in GIS, remote sensing, and AI. My passion is to use geospatial technology for social and environmental good. Feel free to contact me.
  </p>

theme: jekyll-theme-minimal
